# Site settings
title:       Kevin Bastien
email:       kevinjbastien@gmail.com
author:      Kevin Bastien
description: "I am a developer and aspiring designer interested in tech and startups."
baseurl:     ""
url:         "http://blog.kevinbastien.com"

# Google analytics
google_analytics: UA-52211210-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: kbastien
twitter_username: kevinjbastien
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
compressed: true
